### ISSUE TITLE
OCC - cross compilation for Android

### ISSUE THREAD

**Issue by alanliska** [peterspackman/occ#12]
Attempt to cross-compile OCC for Android using either the newest official Google NDK (r26c, based on LLVM-clang version 17), or the previous (r25b, based on LLVM-clang, version 14) failed with this error:

...
[ 72%] Building CXX object src/io/CMakeFiles/occ_io.dir/moldenreader.cpp.o
In file included from /home/debian/OCC/occ/src/io/moldenreader.cpp:8:
In file included from /home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/scan.h:20:
In file included from /home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/detail/scan.h:20:
/home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/detail/args.h:644:11: error: no matching constructor for
     initialization of 'scn::basic_scan_args<scn::basic_scan_context<char>>'
       : basic_scan_args{scan_arg_store<Context, Args...>::desc,
         ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/detail/scan.h:79:50: note: in instantiation of function template
     specialization 'scn::basic_scan_args<scn::basic_scan_context<char>>::basic_scan_args<std::basic_string<char>, int,
     int, double, double, double>' requested here
   auto result = vscan(SCN_FWD(source), format, args);
                                                ^
/home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/detail/scan.h:117:20: note: in instantiation of function
     template specialization 'scn::detail::scan_impl<char, std::basic_string<char>, int, int, double, double, double,
     std::basic_string<char> &, scn::basic_scan_format_string<char, std::basic_string<char> &, std::basic_string<char>,
     int, int, double, double, double>>' requested here
   return detail::scan_impl<char, Args...>(SCN_FWD(source), format, {});
                  ^
/home/debian/OCC/occ/src/io/moldenreader.cpp:105:18: note: in instantiation of function template specialization
     'scn::scan<std::basic_string<char>, int, int, double, double, double, std::basic_string<char> &, void>' requested
     here
           scn::scan<std::string, int, int, double, double, double>(m_current_line, "{} {} {} {} {} {}");
                ^
/home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/detail/args.h:691:15: note: candidate constructor not viable: no
     known conversion from 'std::array<scn::basic_scan_arg<scn::basic_scan_context<char>>, 6>::value_type *' (aka
     'scn::basic_scan_arg<scn::basic_scan_context<char>> *') to 'detail::arg_value *' for 2nd argument
   constexpr basic_scan_args(size_t desc, detail::arg_value* values)
             ^
/home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/detail/args.h:695:15: note: candidate constructor not viable: no
     known conversion from 'std::array<scn::basic_scan_arg<scn::basic_scan_context<char>>, 6>::value_type *' (aka
     'scn::basic_scan_arg<scn::basic_scan_context<char>> *') to 'basic_scan_args<scn::basic_scan_context<char>> *' for
     2nd argument
   constexpr basic_scan_args(size_t desc, basic_scan_args<Context>* args)
             ^
/home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/detail/args.h:642:28: note: candidate constructor template not
     viable: requires single argument 'store', but 2 arguments were provided
   constexpr /*implicit*/ basic_scan_args(
                          ^
/home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/detail/args.h:631:7: note: candidate constructor
     (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class basic_scan_args {
     ^
/home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/detail/args.h:631:7: note: candidate constructor
     (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
/home/debian/OCC/occ/build/_deps/scnlib-src/include/scn/detail/args.h:634:15: note: candidate constructor not viable:
     requires 0 arguments, but 2 were provided
   constexpr basic_scan_args() = default;
             ^
1 error generated.
make[2]: *** [src/io/CMakeFiles/occ_io.dir/build.make:290: src/io/CMakeFiles/occ_io.dir/moldenreader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2699: src/io/CMakeFiles/occ_io.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
...

For the pre-tests purpose, I tried to remove the Molden-associated content from the files catch_debug_console.cpp, dft_tests.cpp, io_tests.cpp, moldenreader.cpp, pair_energy.cpp, wavefunction.cpp. After that, it was possible finish the compilation procedure at least  from the technical point of view (of course, the Molden functionalities would be corrupted). The following procedure was used:

Detailed procedure in WSL (Debian):
========================
(1) prepare the environment
export CC=/path/to/Android/NDK/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi34-clang
export CXX=/path/to/Android/NDK/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi34-clang++
export FC=""
(because there is no official Fortran support in Android NDK)
export CFLAGS=-fPIC
export CXXFLAGS=-fPIC
export LDFLAGS="-fPIC -static-libstdc++"
(-fPIC because starting from Android 5, only position independent executables are supported)
(-static-libstdc++ to avoid adding libstdc++_shared.so from Android NDK to the APK installer)

(2) configure the build
mkdir build
cd build
cmake .. -DBUILD_FPIC=ON -DCMAKE_INSTALL_PREFIX=/path/to/install

(3) if the build is supposed to end up successfully (up to 'make install'), the blocks containing the 'execute_process' command in the catch-testing stage (_deps/catch-src/extras/CatchAddTests.cmake file) were commented (this part is not working in the cross-compilation, since the produced executables are intended to be run, which is not possible due to different ABI)

...

 execute_process(
      COMMAND ${_TEST_EXECUTOR} "${_TEST_EXECUTABLE}" ${spec} --list-tests --verbosity quiet
      OUTPUT_VARIABLE output
      RESULT_VARIABLE result
      WORKING_DIRECTORY "${_TEST_WORKING_DIR}"
    )
   if(NOT ${result} EQUAL 0)
      message(FATAL_ERROR
        "Error running test executable '${_TEST_EXECUTABLE}':\n"
        "  Result: ${result}\n"
        "  Output: ${output}\n"
      )
    endif() 
...
   execute_process(
        COMMAND ${_TEST_EXECUTOR} "${_TEST_EXECUTABLE}" ${spec} ${reporter_arg} --list-reporters
        OUTPUT_VARIABLE reporter_check_output
        RESULT_VARIABLE reporter_check_result
        WORKING_DIRECTORY "${_TEST_WORKING_DIR}"
      )
      if(${reporter_check_result} EQUAL 255)
        message(FATAL_ERROR
          "\"${reporter}\" is not a valid reporter!\n"
        )
      elseif(NOT ${reporter_check_result} EQUAL 0)
        message(FATAL_ERROR
          "Error running test executable '${_TEST_EXECUTABLE}':\n"
          "  Result: ${reporter_check_result}\n"
          "  Output: ${reporter_check_output}\n"
        )
     endif()
...

(4) make
(5) make install

At the end, the binary seemed to be working in Android environment, e.g.
export HOME=/data/data/testing-app-path/files ; cd $HOME ; export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME ; export OCC_DATA_PATH=/path/to/share/occ ; ./occ scf water.xyz b3lyp sto-3g
produced a meaningful output :-).

However, the Molden functionality would be great to retain, thus to fix the above error.

**Comment by peterspackman** [comment]
I've reproduced the issue (both when using the android SDK r26c and r26d).

If I'm honest, I have a feeling this is a compiler bug or something similar, as adjusting the same code to only e.g. read 5 of the values works just fine (with the issue of not reading all the data we need). 

The same code also compiles and runs without issue on gcc, and apple clang, and given it's not really in my code (but something to do with the templated types in scnlib) I'm hesitant to spend too much time figuring it out.

May I suggest just patching the code for now to read something like this instead using string streams (just the relevant method in `moldenreader.cpp`)

```cpp
        std::istringstream iss(m_current_line);

        std::string symbol;
        int idx, num;
        double x, y, z;

        if (iss >> symbol >> idx >> num >> x >> y >> z) {
            atom.atomic_number = num;
            atom.x = x;
            atom.y = y;
            atom.z = z;
            if (factor != 1.0) {
                atom.x *= factor;
                atom.y *= factor;
                atom.z *= factor;
            }
            m_atoms.push_back(atom);
        } else {
            throw std::runtime_error("unable to read atom line");
        }
    }
```
instead of the existing code:

```cpp
        auto scan_result =
            scn::scan<std::string, int, int, double, double, double>(m_current_line, "{} {} {} {} {} {}");
        auto &[symbol, idx, num, x, y, z] = scan_result->values();

        atom.atomic_number = num;
        atom.x = x;
        atom.y = y;
        atom.z = z;

        if (factor != 1.0) {
            atom.x *= factor;
            atom.y *= factor;
            atom.z *= factor;
        }
        m_atoms.push_back(atom);
```

That compiles without issue, should work the same (albeit a bit slower) and should give you molden reading support for now. I'll keep this issue open in case things come up again, but for now I hope a workaround is enough!

**Comment by alanliska** [comment]
Thanks a lot 👍 - I agree with you, the outlined patch works well. Now the program seems to be working with all the features.
