### ISSUE TITLE
Error when reading negative ion charge from Gaussian input

### ISSUE THREAD

**Issue by alanliska** [peterspackman/occ#13]
Linux (x86_64) as well as all Android OCC variants (arm, aarch64, x86, x86_64) work well with Gaussian style inputs

/path/to/occ input.gjf

when the molecular charge is zero, or positive. However, if the charge is negative, as e.g. in the case of hydroxide ion, the calculation fails with uncorrect read-in (the returned charge -2147483648 is erroneous). 

The sample input:

#HF/STO-3G

desc

-1 1
O  0.000000  0.000000  0.000000 
H  1.300000  0.000000  0.000000 

The output:

         Open
          \
           Comp
            \
             Chem

a library and program for quantum chemistry

copyright (C) 2020-2024 Peter Spackman

this version of occ makes use of the following third party libraries:

CLI11                command line argument parser
eigen3               Linear Algebra (v 3.4.0)
fmt                  String formatting (v 10.2.0)
gau2grid             Gaussian basis function evaluation (v 2.0.7)
gemmi                CIF parsing & structure refinement (v 0.6.5)
LBFGS++              L-BFGS implementation
libcint              Electron integrals using GTOs (v "6.1.1")
libecpint            Electron integrals for ECPs (v 1.0.7)
libxc                Density functional implementations (v 6.2.2)
nanoflann            KDtree implementation
nlohmann::json       JSON parser
phmap                Fast hashmap implementation
pocketFFT            Standalone implementation of fast Fourier transform
scnlib               String parsing
spdlog               Logging (v 1.12.0)
subprocess           Calling external subprocesses
tinyply              Writing .ply (mesh) files in binary/ASCII format

Parallelization: 1 OpenMP threads, 1 eigen threads
Driver: energy
===============================  Input  ================================
Method string                          hf
Basis name                         sto-3g
Shell kind                      Cartesian
Net charge                    -2147483648
Multiplicity                            1
Geometry 'input.gjf' (au)  ---------------------------------------------
 O      0.000000     0.000000     0.000000
 H      2.456644     0.000000     0.000000
Inertia tensor (x 10e-46 kg m^2)  --------------------------------------
    0.000000    -0.000000    -0.000000
   -0.000000     0.266096    -0.000000
   -0.000000    -0.000000     0.266096
Principal moments of inertia  ------------------------------------------
    0.000000     0.266096     0.266096
Rotational constants (GHz)  --------------------------------------------
    0.000000   315.375914   315.375914

Gas-phase properties (at 298.15 K)  ------------------------------------
Rotational free energy         54.869119 kJ/mol
Translational free energy     -34.317947 kJ/mol
Loaded basis set: cartesian
Number of shells:            4
Number of  basis functions:  6
Maximum angular momentum:    1
Spinorbital kind: restricted
exception:
    Invalid charge: systems with no electrons are not supported
terminating program.

****************** Backtrace Start ******************
Reading JSON basis Z = 50
inserting: basis for Z = 50
Reading JSON basis Z = 51
inserting: basis for Z = 51
Reading JSON basis Z = 52
inserting: basis for Z = 52
Reading JSON basis Z = 53
inserting: basis for Z = 53
Reading JSON basis Z = 54
inserting: basis for Z = 54
Reading JSON basis Z = 6
inserting: basis for Z = 6
Reading JSON basis Z = 7
inserting: basis for Z = 7
Reading JSON basis Z = 8
inserting: basis for Z = 8
Reading JSON basis Z = 9
inserting: basis for Z = 9
Loaded basis set: cartesian
Number of shells:            4
Number of  basis functions:  6
Maximum angular momentum:    1
computing shellpairs (threshold = 1e-12, kind = cartesian
significant shellpairs = 10 (10 total)
Spinorbital kind: restricted
Setting integral precision: 1e-12
9 active electrons
0 frozen electrons
Setting system charge: 4294967295
Setting system multiplicity: 1
Setting charge = -2147483648, multiplicity = 1 in scf
exception:
    Invalid charge: systems with no electrons are not supported
terminating program.

****************** Backtrace End ********************

**Comment by peterspackman** [comment]
Thanks for spotting this, I don't really use the gaussian input parsing (was just quickly hacked together early on in the development). Thankfully the fix looks to be trivial, for some reason the charge in the input was stored as an unsigned int (which is obviously wrong).

I'll fix this in my current development version, do you need it to be backported (can always just patch `include/occ/io/gaussian_input_file.h' and change the variable type too)?

**Comment by peterspackman** [comment]
Should be done as of 2cff659e586149452123d91c0399dffd9dc65fe4

So I'll close this as completed, and I've made a new issue for the solvation settings reading #14
