### ISSUE TITLE
Segfault when supplying wrong dft grid options:

### ISSUE THREAD

**Issue by FlorianKleemiss** [peterspackman/occ#6]
When using dft_grid_max_angular and making the value smaller than the default min value there is a segfault (understandably).

suggestions: Maybe atch these with error message or reduce min_angular to something smaller upon request of change?

command line to reproduce:
occ sucrose.xyz pbe cc-pvtz -d def2-universal-jkfit -t 6 --dft_grid_max_angular 20

**Comment by peterspackman** [comment]
Thanks for pointing that out - I'll sort it out today. It's an easy fix.

**Comment by peterspackman** [comment]
Should be fixed as of 6a30af5
