### ISSUE TITLE
OCC CG values printed are the same

### ISSUE THREAD

**Issue by NathandB94** [peterspackman/occ#9]
I have been doing calculations and I have been getting the same values printed for different solvents apart from the total E.

I have attached an example of a few of my results I have been collecting:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/Nathan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/Nathan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

solvent | lattice energy (crystal) mol 1 | rotational free energy (molecule) mol 1 | dH sublimation mol 1 | dS sublimation mol 1 | dG sublimation mol 1 | dG solution mol 1 | equilibrium_constant mol 1 | log S mol 1 | solubility (g/L) mol 1 | Total E_int mol 1
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
water | -134.962 | -32.477 | 130.006 | -74.894 | 55.112 | -8.922 | 3.66 | 1.564 | 5.54 | 155.988
ethylethanoate | -134.962 | -32.477 | 130.006 | -74.894 | 55.112 | -8.922 | 3.66 | 1.564 | 5.54 | 165.782
methanol | -134.962 | -32.477 | 130.006 | -74.894 | 55.112 | -8.922 | 3.66 | 1.564 | 5.54 | 138.801
acetonitrile | -134.962 | -32.477 | 130.006 | -74.894 | 55.112 | -8.922 | 3.66 | 1.564 | 5.54 | 155.549
dimethylsulfoxide | -134.962 | -32.477 | 130.006 | -74.894 | 55.112 | -8.922 | 3.66 | 1.564 | 5.54 | 165.771

</body>

</html>

**Comment by NathandB94** [comment]
I used the CIF HXACAN01

**Comment by peterspackman** [comment]
Yep, it's already been fixed in the most recent version after commit: [6ec91ba](https://github.com/peterspackman/occ/commit/6ec91ba9b40867e122b5263e60944b4383543362)

**Comment by NathandB94** [comment]
Thanks very much! I downloaded the new version and it works!
